stages:
  - build
  - test

build:
  stage: build
  image: gradle:8.5-jdk17
  script:
    - ./gradlew clean build

integration-test:
  stage: test
  image: gradle:8.5-jdk17
  script:
    - ./gradlew bootRun &              
    - sleep 15                          
    - npm install -g newman
    - newman run 1dv027-API.postman_collection.json