stages:
  - build
  - integration-test

build:
  stage: build
  image: gradle:8.5-jdk17
  script:
    - ./gradlew clean build

integration-test:
  stage: integration-test
  image: gradle:8.5-jdk17
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
  script:
    - ./gradlew bootRun &
    - sleep 15
    - npm install -g newman
    - newman run 1dv027-API.postman_collection.json
