stages:
  - build
  - integration-test

build:
  stage: build
  image: gradle:8.5-jdk17
  script:
    - ./gradlew clean build

integration-test:
  stage: integration-test
  image: gradle:8.5-jdk17
  before_script:
    - apt-get update && apt-get install -y curl ca-certificates gnupg
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
  script:
    - echo 'DB_URL=jdbc:postgresql://localhost:5432/books_database' >> app/.env
    - echo 'DB_USER=postgres' >> app/.env
    - echo 'DB_PASSWORD=lassokastning' >> app/.env
    - echo 'JWT_SECRET=C3UE0DCjvlu1Do0T/yeEJPEMgIplHVlacNtxCh5bqxk=' >> app/.env
    - ./gradlew bootRun &
    - echo "Waiting for server to be ready..."
    - until curl -s http://localhost:8080/graphql > /dev/null; do echo "Still waiting..."; sleep 2; done
    - echo "Server is up!"
    - npm install -g newman
    - newman run 1dv027-API.postman_collection.json
    #Putting the .env in this file (I KNOW WE SHOULD NOT DO THIS) since I am not maintainer and cannot set the env variables in the settings.
