name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 20

      - name: Build Spring Boot
        run: |
          ./gradlew clean build

      - name: Set up Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build React frontend (Vite)
        run: |
          cd frontend/react-frontend
          npm install
          npm run build

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.ID_GITHUB }}
          script: |
            cd /var/www/wt2
            docker compose pull
            docker compose up -d