name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 20

      - name: Build Spring Boot
        run: |
          ./gradlew clean build

      - name: Set up Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build React frontend (Vite)
        run: |
          cd frontend/react-frontend
          npm install
          npm run build
